url: http://punderthings.com
baseurl: 

# Site & head/header settings
title: Punderthings Consulting
intro-lead-in: Welcome To Punderthings℠!
intro-heading: A better way to engage with open source
team-heading: Punderthings Leadership
team-subheading: Trusted and proven FOSS expertise.
team-trailer: I've been working with Apache projects for almost 20 years; now I'd like to help <b>your</b> organization with open source!  Email me: <a href="mailto:shane@punderthings.com">shane@punderthings.com</a>
email: shane@punderthings.com
author: Shane Curcuru
authorurl: http://shanecurcuru.org/
description: &description "A better way to engage in open source - consulting for businesses and communities."

# Team names, titles and social links
people:
- name: Shane Curcuru
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/ShaneCurcuru

- name: Tokaji
  pic: 2
  position: Troublemaker
  social:
    - title: instagram
      url: https://www.instagram.com/shanecurcuru/

- name: Pálinka
  pic: 3
  position: Peacemaker
  social:
    - title: instagram
      url: https://www.instagram.com/shanecurcuru/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/ShaneCurcuru
  - title: linkedin
    url: https://www.linkedin.com/in/ShaneCurcuru
  - title: stack-overflow
    url: https://stackexchange.com/users/7027028/shane-curcuru
  - title: book
    url: http://CommunityOverCode.com/
  - title: cubes
    url: http://ShaneSlides.com/
  - title: heart-o
    url: http://whyilovetheasf.com/

# Postal address (add as many lines as necessary)
address:
  - line: 1347 Massachusetts Ave, Box 750040
  - line: Arlington, MA 02475

# Build settings
markdown: kramdown
permalink: pretty
